options:
  formatter: stylish
  merge-default-rules: true
  max-warnings: 0
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**'
    - 'coverage/**'
    - 'dist/**'
    - 'test/**'
    - 'page/sass/commit_funds.scss'
    - 'page/sass/common.scss'
    - 'page/sass/easy_access.scss'
    - 'page/sass/ecosystem.scss'
    - 'page/sass/footer.scss'
    - 'page/sass/global.scss'
    - 'page/sass/participating.scss'
    - 'page/sass/pictures.scss'
    - 'page/sass/press.scss'
    - 'page/sass/vex-modal.scss'
    - 'page/sass/whitepaper.scss'
    - 'app/components/HexagonsStack.scss'
    - 'app/components/Incentive.scss'
    - 'page/sass/product_menu.scss'
    - 'page/sass/product.scss'
rules:
  property-sort-order:
    - 1
    - order: concentric
