dist: trusty
sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "7"
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn --pure-lockfile
before_script: greenkeeper-lockfile-update
script:
  - set -e                     # fail fast
  - yarn lint
  - yarn test:coverage
after_script: greenkeeper-lockfile-upload
