header:
  id: "product-header"
  menu_text: "Introduction"
  title: "Participate in global innovation with the Neufund Platform"
  content: |
    <p>Neufund opens and re-imagines Initial Coin Offerings (ICOs) for all types of companies and investors. It combines the advantages of classical equity investment with the efficiency of ICO fundraising.</p>
    <p>The Neufund Platform is designed to be both secure and user friendly.</p>

  yt_video: "W0LHTWG-UmQ"
who_can_use:
  id: "who_can_use"
  menu_text: "The two sides of the Neufund Platform"
  bg_url: ""
  white: true
  purple_title: false
  title: "Two sides of the Neufund Platform"
  headline: "A platform for investors and companies"
  backgroundText: ""
  paragraphs:
    - "The Neufund Platform is designed for both sides of the investment process. It allows any kind of investor, be it individuals, business angels or institutional investors to access high-quality and diverse deals."
    - "It enables companies from all over the world, both seed and late stage to access a unique network of investors with broad expertise  and interest in funding any kind of innovation."
  images:
    - "assets/screenshots/group-25"
    - "assets/screenshots/group-27"

demistifying_blockchain:
  id: "demistifying_blockchain"
  menu_text: "Demystifying blockchain"
  bg_url: ""
  bg_db: false
  white: true
  purple_title: false
  title: "Demystifying blockchain"
  headline: "Effortless blockchain on-boarding"
  backgroundText: ""
  paragraphs:
    - "Neufund opens the process of an ICO to a broader audience by offering a much simpler and safer sign-up with a user-friendly web wallet. As your investment grows, you can upgrade your wallet to a hardware wallet which provides better protection for your funds. "
    - "You will be able to become a part of the crypto-world with a simple wire transfer and invest on the platform with a stable Euro Token. This way you do not have to own ETH to start participating."
    - "For blockchain experts Neufund integrates a sign-up with a Ledger Nano S and all kinds of web3 wallets. "
  image: assets/platform/0.ChooseOption

investors_dashboard:
  id: "investors_dashboard"
  menu_text: ""
  purple_title: false
  backgroundText: "For investors"
  bg_url: "/assets/svg-bg/blue.svg"
  white: false
  title: "Manage your investments on the Neufund Platform with an easy-to-use dashboard"
  image: "assets/platform/InvestorsDashboard"

main_feature:
  id: "main_feature"
  menu_text: "Investing"
  bg_url: ""
  bg_db: false
  white: false
  purple_title: false
  title: "Invest in innovation on blockchain"
  headline: "Equity Token Offering - the new type of investment mechanism"
  backgroundText: ""
  paragraphs:
    - Initial Coin Offerings (ICOs) are a new powerful method for fundraising. With Neufund's innovative approach, it is now possible for companies to legally tokenize their equity and for investors to participate in Equity Token Offerings (ETOs) on the Blockchain. Neufund’s legal and technical framework allows to represent actual company shares in the form of equity tokens on-chain and gives full shareholder rights. On top of that, based on the decision of the company equity tokens may be transferred or traded on external secondary markets.
    - Neufund's ETOs democratise the investment process once and for all.
  image: "assets/platform/0.Platform"

invisible_blockchain:
  id: "invisible_blockchain"
  menu_text: "You have control"
  bg_url: ""
  white: false
  purple_title: false
  title: "Stay in control of your funds"
  headline: "Invest with crypto and stable coins"
  backgroundText: ""
  paragraphs:
    - If you are a crypto investor holding ETH, you can invest in companies and withdraw payouts in ETH. If you are an off-chain investor or a blockchain newbie, you can now invest in companies and withdraw payouts in Euro Tokens (internal stable coin) with a simple wire transfer.
    - All investments are denominated in Euro to protect you from the high volatility of cryptocurrencies. Euro Tokens are pegged 1:1 to Euro and serve as a purely internal tool.
  images:
    - "assets/platform/investment_account_EURT"
    - "assets/platform/investment_account_ETH"

benefits_of_blockchain:
  id: "benefits_of_blockchain"
  menu_text: "Benefits of tokenization"
  bg_url: ""
  bg_db: true
  white: false
  purple_title: false
  title: "Benefits of tokenization"
  headline: "Profits from equity tokens: ROI & high liquidity"
  backgroundText: ""
  paragraphs:
    - The Neufund Platform automatically distributes proceeds to all equity token holders. You can claim your dividends or proceeds from the given company’s exit via the simple UI.
    - The beauty of the secondary market is its liquidity. By investing in equity tokens on the Neufund Platform, your assets stay liquid. You can sell our buy more equity tokens if you like. Terms of the ETOs are backed by investment agreements which correspond to those usually found in typical shareholder agreements. As an equity token holder, you enjoy key shareholder rights such as reports, voting in shareholder resolutions, anti-dilution protections, etc.
  image: "assets/platform/I-IN-OWN"

startups_dashboard:
  id: "startups_dashboard"
  menu_text: ""
  backgroundText: "For companies"
  purple_title: true
  bg_url: "/assets/svg-bg/purple.svg"
  white: true
  title: "Create your company profile in no time"
  image: "assets/platform/StartupProfile-Edit"

disrupting_fundraising:
  id: "disrupting_fundraising"
  menu_text: "Being invested in"
  bg_url: ""
  white: true
  purple_title: true
  title: "You set the terms"
  headline: "Define the termsheet on-chain"
  backgroundText: ""
  paragraphs:
    - "The Neufund Platform provides a legal and technical framework to ensure an easy and fully-legal Equity Token Offering. To ease your work, we propose a standard termsheet for the ETO. However, you are in charge of setting all the commercial terms using your company dashboard on the platform."
    - "<i class=\"material-icons\">link</i> <a href=\"https://neufund.org/docs/eto\">Neufund - Equity Token Offerings</a><br/><i class=\"material-icons\">link</i> <a href=\"https://neufund.org/docs/etofaqs\">Neufund - FAQs for companies</a>"
  images:
    - assets/platform/StartupsAccount-Dashboard4
    - assets/platform/StartupsAccount-Dashboard7

post_investment_management_tool:
  id: "post_investment_management_tool"
  menu_text: "Managing investors"
  bg_url: ""
  white: true
  purple_title: true
  title: "Raise your funds with an ETO"
  headline: "Offer your equity tokens to investors"
  backgroundText: ""
  paragraphs:
    - "You can now launch your ETO and offer your equity tokens to all the investors on the Neufund Platform. After a successful ETO, you will sign an Investment Agreement with a Nominee representing your token holders off-chain. Hereafter, you will be able to access all the funds you raise."
    - "The Nominee will represent all your token holders with one entry in your cap table."
  images:
    - /assets/platform/I-IN-OWN
    - /assets/platform/I-IN-OWN

manage_company:
  id: "manage-company"
  menu_text: "Manage Company"
  bg_url: ""
  white: true
  purple_title: true
  title: "After the ETO"
  headline: "Manage your tokenized company on-chain"
  backgroundText: ""
  paragraphs:
    - "The dashboard will allow you to interact with your token holders. You will be able to report to all your token holders, enable voting in shareholder resolutions and distribute dividends. This way you can manage numerous token holders without the burden of logistics."
  images:
    - /assets/platform/StartupsDashboard

neufund_profile:
  id: "neufund_profile"
  menu_text: ""
  backgroundText: ""
  purple_title: false
  bg_url: ""
  white: true
  title: "Neufund's profile on the Platform"
  image:
    - url: "screenshots/StartupsCorporateGovernance.png"
      width: 574
    - url: "screenshots/StartupsCorporateGovernance_2x.png"
      width: 1148
    - url: "screenshots/StartupsCorporateGovernance_3x.png"
      width: 1722
reward_revenue:
  id: "reward_revenue"
  menu_text: "Co-owning the ecosystem"
  bg_url: ""
  white: true
  headline: ""
  content:
    - title: "Reward"
      icon: "alarm_off"
      content: "icbm, invest"
      link: "#"
    - title: "Revenue token"
      icon: "autorenew"
      content: "Fees, equity"
      link: "#"
    - title: "Traded"
      icon: "backup"
      content: "On secondary market"
      link: "#"
feature_by_feature:
  id: "feature_by_feature"
  menu_text: "Neufund Platform Features"
  bg_url: ""
  white: true
  headline: "Neufund Platform Features"
  content:
    - title: "LEGALLY BINDING EQUITY TOKENS"
      icon: "assets/platform/icons/invest.svg"
      content: "Invest fully legally in Equity Token Offerings in potentially any company in the world."
    - title: "STABLE COIN"
      icon: "assets/platform/icons/stable-coin.svg"
      content: "Investment transactions may happen in Euro-Token (EURT), a stable internal token pegged 1:1 to the Euro. But we also accept ETH investments."
    - title: "PROCEEDS DISTRIBUTION"
      icon: "assets/platform/icons/fees.svg"
      content: "The Platform automatically distributes proceeds to all token holders."
    - title: "ON-CHAIN GOVERNANCE"
      icon: "assets/platform/icons/governance.svg"
      content: "ETOs are backed by investment agreements which correspond to those usually found in typical shareholder agreements."
    - title: "STANDARD KYC"
      icon: "assets/platform/icons/aml.svg"
      content: "ETO investors can be individuals or organisations. We have standard KYC/AML procedures like you would expect from other financial institutions, e.g. banks."
    - title: "SECURITY"
      icon: "assets/platform/icons/security.svg"
      content: "We plan to support three different authentication mechanisms. In addition, all our users will benefit from a protective wallet contract."

last:
  id: "last"
  menu_text: ""
  bg_url: ""
  white: true
  headline: "Become a part of the Neufund ecosystem!"
  button_text: "Participate in the ICBM"
  button_url: "/commit"
  link_text: "Read more about Neufund ICBM"
  link_url: "/"
