header:
  id: "product-header"
  menu_text: "Introduction"
  title: "A true platform<br/>for the people."
  content: "Easy to use, crafted experience for different actors on different stages of their investment journey. An on-going work, being built with community for community in a culture of open-source, access point for everyone to blockchain."
  yt_video: "W0LHTWG-UmQ"
who_can_use:
  id: "who_can_use"
  menu_text: "Who can use the Platform"
  bg_url: ""
  white: false
  purple_title: false
  title: "Who can use Neufund's Platform"
  headline: "For startups and all kinds of investors"
  backgroundText: ""
  paragraphs:
    - "Unless you are a partner in the VC fund or a business angel, you are new to investing in the companies equity. Neufund’s goal is to open this market. The platform is designed and built with a thought to anticipate the needs of startups and investors, both individual and institutional.  Its key values are: accessibility, scalability and integrability with the traditional investment world."
  images:
    - - url: "screenshots/group-25.png"
        width: 209
      - url: "screenshots/group-25_2x.png"
        width: 418
      - url: "screenshots/group-25_3x.png"
        width: 627
    - - url: "screenshots/group-27.png"
        width: 169
      - url: "screenshots/group-27_2x.png"
        width: 338
      - url: "screenshots/group-27_3x.png"
        width: 507
main_feature:
  id: "main_feature"
  menu_text: "Investing"
  bg_url: ""
  bg_db: false
  white: true
  purple_title: false
  title: "Main feature: invest in startups"
  headline: "ICO: new investment mechanism for every model"
  backgroundText: ""
  paragraphs:
    - Initial Coin Offering is a new powerful tool for fundraising. With Neufund's innovative approach to allow investments in tokenized shares, it is becoming main-stream. It allows both on- and off-chain startups to address at once a huge capital pool making the fundraising cheap and fast. It allows investors to invest in the projects they believe in, and along with experienced VCs. Neufund's ICO democratises the investment process!
  image:
    - url: "screenshots/MainPage.png"
      width: 604
    - url: "screenshots/MainPage_2x.png"
      width: 1208
    - url: "screenshots/MainPage_3x.png"
      width: 1812
invisible_blockchain:
  id: "invisible_blockchain"
  menu_text: "What are the tokens"
  bg_url: ""
  white: true
  purple_title: false
  title: "(in)visible blockchain"
  headline: "Invest with tokens in tokens"
  backgroundText: ""
  paragraphs:
    - Design and used by nerds and for nerds blockchain products often seem complex and discouraging. Neufund's goal is blockchain's demystification and seamless transition from traditional systems for everyone.
    - In practice it means simple wiring of crypto-funds to the Platform's investment account, and couple clicks to invest on blockchain in the real shares, which then as equity tokens are stored in an investor's portfolio.
    - Neufund creates the new set of industry standards integrated with the legal systems.
  images:
    - - url: "screenshots/Investment-Accounts.png"
        width: 428
      - url: "screenshots/Investment-Accounts_2x.png"
        width: 856
      - url: "screenshots/Investment-Accounts_3x.png"
        width: 1284
    - - url: "screenshots/Portfolio-Equity.png"
        width: 480
      - url: "screenshots/Portfolio-Equity_2x.png"
        width: 960
      - url: "screenshots/Portfolio-Equity_3x.png"
        width: 1440
benefits_of_blockchain:
  id: "benefits_of_blockchain"
  menu_text: "Benefits of blockchain"
  bg_url: ""
  bg_db: true
  white: true
  purple_title: false
  title: "Benefits of blockchain"
  headline: "Profit from the tokens: proceeds and secondary market"
  backgroundText: ""
  paragraphs:
    - Secondary market = liquidity.
    - Asset liquidation possible for investors and startups from day one after ICO (secondary market drives primary market of innovation) assuring efficient investment decisions and instant capitalisation.
    - The Platform provides a mechanism for the  distribution of the fees and proceeds to token holders. Since the primary value of equity tokens is economic, the proceeds distribution is the investors’ fundamental right. Such proceeds are deposited into an equity token distribution pool where they may be claimed by token holders.
  image:
    - url: "screenshots/I-IN-OWN.png"
      width: 604
    - url: "screenshots/I-IN-OWN_2x.png"
      width: 1208
    - url: "screenshots/I-IN-OWN_3x.png"
      width: 1812
investors_dashboard:
  id: "investors_dashboard"
  menu_text: ""
  purple_title: false
  backgroundText: "For investors"
  bg_url: "/assets/svg-bg/blue.svg"
  white: true
  title: "Investors dashboard"
  image:
    - url: "screenshots/InvestorsDashboard.png"
      width: 790
    - url: "screenshots/InvestorsDashboard_2x.png"
      width: 1580
    - url: "screenshots/InvestorsDashboard_3x.png"
      width: 2370
startups_dashboard:
  id: "startups_dashboard"
  menu_text: ""
  backgroundText: "For startups"
  purple_title: true
  bg_url: "/assets/svg-bg/purple.svg"
  white: false
  title: "Startups Dashboard"
  image:
    - url: "screenshots/StartupsDashboard.png"
      width: 790
    - url: "screenshots/StartupsDashboard_2x.png"
      width: 1580
    - url: "screenshots/StartupsDashboard_3x.png"
      width: 2370
disrupting_fundraising:
  id: "disrupting_fundraising"
  menu_text: "Being invested in"
  bg_url: ""
  white: false
  purple_title: true
  title: "Disrupting fundraising"
  headline: "Accessible investors pool and symmetry of information"
  backgroundText: ""
  paragraphs:
    - "There are couple of elements in startup fundraising that can go wrong:"
    - "- an inoperable network — meaning lack of access to people with capital and interest in the particular startup and"
    - "- an assymmetrical information distribution — a novice founder seating in the negotiations room with an experienced investor with the army of lawyers"
  image:
    - url: "screenshots/CompanysICOProfile.png"
      width: 563
    - url: "screenshots/CompanysICOProfile_2x.png"
      width: 1126
    - url: "screenshots/CompanysICOProfile_3x.png"
      width: 1689
post_investment_management_tool:
  id: "post_investment_management_tool"
  menu_text: "Managing investors"
  bg_url: ""
  white: false
  purple_title: true
  title: "Post-investment management tool"
  headline: "Investors relations "
  backgroundText: ""
  paragraphs:
    - "If you have previous experience with fundraising you know this: investors relations are the bread and butter of every founder. Neufund Platform allows managers to easly inform both on- and off-chain investors about the changes in their day to day operations and set up the voting which would be effectively equal to traditional shareholder meeting."
  images:
    - - url: "screenshots/StartupsCorporateGovernance.png"
        width: 574
      - url: "screenshots/StartupsCorporateGovernance_2x.png"
        width: 1148
      - url: "screenshots/StartupsCorporateGovernance_3x.png"
        width: 1722
    - - url: "screenshots/StartupsCorporateGovernance_Investor.png"
        width: 434
      - url: "screenshots/StartupsCorporateGovernance_Investor_2x.png"
        width: 868
      - url: "screenshots/StartupsCorporateGovernance_Investor_3x.png"
        width: 1302
neufund_profile:
  id: "neufund_profile"
  menu_text: ""
  backgroundText: ""
  purple_title: false
  bg_url: ""
  white: true
  title: "Neufund's profile on the Platform"
  image:
    - url: "screenshots/StartupsCorporateGovernance.png"
      width: 574
    - url: "screenshots/StartupsCorporateGovernance_2x.png"
      width: 1148
    - url: "screenshots/StartupsCorporateGovernance_3x.png"
      width: 1722
reward_revenue:
  id: "reward_revenue"
  menu_text: "Co-owning the ecosystem"
  bg_url: ""
  white: true
  headline: ""
  content:
    - title: "Reward"
      icon: "alarm_off"
      content: "icbm, invest"
      link: "#"
    - title: "Revenue token"
      icon: "autorenew"
      content: "Fees, equity"
      link: "#"
    - title: "Traded"
      icon: "backup"
      content: "On secondary market"
      link: "#"
feature_by_feature:
  id: "feature_by_feature"
  menu_text: "Feature by feature"
  bg_url: ""
  white: false
  headline: "Feature by feature"
  content:
    - title: "Invest in legal equity tokens"
      icon: "help"
      content: "Invest fully legally in ICOs of equity tokens or utility tokens in any company in the world. Neufund also enables investment in tokens that represents rights other than equity, like utility tokens, protocol tokens, and any tokens backed by a SAFT agreement. We achieve this by formally linking traditional contracts with Ethereum smart contracts through mutual reference and code correspondence. "
      link: "#"
    - title: "Stable coin"
      icon: "trending_up"
      content: "Investment transactions may happen in Euro-Token (EURt), a stable internal token pegged 1:1 to Euro (as explained here). The price of a given equity token is denominated in Euro so that the number of equity tokens acquired by an investor can be directly calculated."
      link: "#"
    - title: "Fees & Proceeds Distribution"
      icon: "gesture"
      content: "The Platform provides a mechanism for the distribution of fees and proceeds to token holders. Since the primary value of equity tokens is economic, the distribution of proceeds is the investors’ fundamental right. These proceeds are deposited into an equity token distribution pool where they may be claimed by token holders. "
      link: "#"
    - title: "On-chain Governance"
      icon: "create"
      content: "The Investment Agreement requires the company to carry out shareholder resolutions on Platform for on-chain investors​. Off-chain investors still vote on paper and results are merged to get the final answer. The voting procedure complies with those usually found in typical shareholder agreement."
      link: "#"
    - title: "KYC/AML"
      icon: "border_right"
      content: "ETO investors can be individuals or organizations. We have standard KYC/AML procedures like you would see on any financial institution, e.g. bank."
      link: "#"
    - title: "Security"
      icon: "cloud_queue"
      content: "Neufund’s user base is expected to include both experts and novices to blockchain applications, and both high and low value accounts. To provide a smooth experience while guaranteeing security for all these users, we plan to support three different authentication mechanisms. In addition, all our users benefit from a protective wallet contract."
      link: "#"
last:
  id: "last"
  menu_text: ""
  bg_url: ""
  white: false
  headline: "Be the owner of Neufund's ecosystem!"
  button_text: "Commit ETH"
  button_url: "#"
  link_text: "Read about Nefund's ICO"
  link_url: "#"
